#!/bin/bash
# Macros: defmacro
source tests/helpers.sh

echo "=== Macro Tests ==="
run_test "defmacro basic" '(do (defmacro my-if [test then-expr] (list (quote if) test then-expr)) (my-if true 42))' '42'
run_test "defmacro false branch" '(do (defmacro my-if [test then-expr] (list (quote if) test then-expr)) (my-if false 42))' 'nil'
run_test "defmacro with arithmetic" '(do (defmacro double [x] (list (quote +) x x)) (+ 1 (double 5)))' '11'
run_test "defmacro variadic" '(do (defmacro my-let [bindings & body] (cons (quote let) (cons bindings body))) (my-let [x 1 y 2] (+ x y)))' '3'
run_test "defmacro returns symbol" '(defmacro my-macro [x] x)' 'my-macro'
run_test "doseq single binding" '(do (def __a (atom [])) (doseq [x [1 2 3]] (swap! __a conj x)) @__a)' '[1 2 3]'
run_test "doseq nested bindings" '(do (def __a (atom [])) (doseq [x [1 2] y [:a :b]] (swap! __a conj (list x y))) @__a)' '[(1 :a) (1 :b) (2 :a) (2 :b)]'
run_test "doseq with computation" '(do (def __a (atom [])) (doseq [x [1 2 3]] (swap! __a conj (* x x))) @__a)' '[1 4 9]'
run_test "doseq empty collection" '(do (def __a (atom [])) (doseq [x []] (swap! __a conj x)) @__a)' '[]'
run_test "doseq returns nil" '(doseq [x [1 2]] x)' 'nil'
run_test "doseq with list" '(do (def __a (atom [])) (doseq [x (list 10 20 30)] (swap! __a conj (inc x))) @__a)' '[11 21 31]'

# for macro - list comprehension
run_test "for single binding" '(doall (for [x [1 2 3]] (* x x)))' '(1 4 9)'
run_test "for identity" '(doall (for [x [1 2 3]] x))' '(1 2 3)'
run_test "for empty collection" '(doall (for [x []] x))' '()'
run_test "for with string" '(doall (for [x ["a" "b" "c"]] (str x "!")))' '("a!" "b!" "c!")'
run_test "for with keyword" '(doall (for [x [:a :b :c]] x))' '(:a :b :c)'
run_test "for with map lookup" '(doall (for [k [:a :b]] (get {:a 1 :b 2} k)))' '(1 2)'
run_test "for nested bindings" '(doall (for [x [1 2] y [:a :b]] (list x y)))' '((1 :a) (1 :b) (2 :a) (2 :b))'
run_test "for nested with computation" '(doall (for [x [1 2] y [3 4]] (+ x y)))' '(4 5 5 6)'
run_test "for nested three levels" '(doall (for [x [1 2] y [3 4] z [5 6]] (list x y z)))' '((1 3 5) (1 3 6) (1 4 5) (1 4 6) (2 3 5) (2 3 6) (2 4 5) (2 4 6))'
run_test "for nested empty inner" '(doall (for [x [1 2] y []] (list x y)))' '()'
run_test "for with :when" '(doall (for [x [1 2 3 4 5] :when (> x 2)] (* x x)))' '(9 16 25)'
run_test "for with :when all filtered" '(doall (for [x [1 2 3] :when (> x 10)] x))' '()'
run_test "for with :when none filtered" '(doall (for [x [1 2 3] :when (< x 10)] x))' '(1 2 3)'
run_test "for with :while" '(doall (for [x [1 2 3 4 5] :while (< x 4)] (* x x)))' '(1 4 9)'
run_test "for with :while stops early" '(doall (for [x [2 4 3 6] :while (even? x)] x))' '(2 4)'
run_test "for with :while first fails" '(doall (for [x [1 2 3] :while (> x 5)] x))' '()'
run_test "for nested with :when" '(doall (for [x [1 2 3] :when (> x 1) y [:a :b]] (list x y)))' '((2 :a) (2 :b) (3 :a) (3 :b))'
run_test "for with range" '(doall (for [x (range 1 6)] (* x x)))' '(1 4 9 16 25)'
run_test "for nested with inner :when" '(doall (for [x [1 2] y [1 2 3] :when (> y x)] (list x y)))' '((1 2) (1 3) (2 3))'
run_test "for with even?" '(doall (for [x [1 2 3 4 5] :when (even? x)] x))' '(2 4)'
run_test "for with odd?" '(doall (for [x [1 2 3 4 5] :when (odd? x)] x))' '(1 3 5)'
run_test "for boolean body" '(doall (for [x [1 2 3]] (> x 1)))' '(false true true)'
run_test "for nil body" '(doall (for [x [1 2 3]] nil))' '(nil nil nil)'
