name: Build and Test

on:
  push:
    branches: [ "main", "test" ]
  pull_request:

jobs:
  build-test-ubuntu:
    uses: ./.github/workflows/build-test-base.yml
    with:
      os: ubuntu-latest

  build-test-macos:
    uses: ./.github/workflows/build-test-base.yml
    with:
      os: macos-latest

  build-test-windows:
    uses: ./.github/workflows/build-test-base.yml
    with:
      os: windows-latest

